# Generated by Django 3.1.4 on 2022-03-28 08:42

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_records_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=records.models.path_and_rename),
        ),
    ]
